environment:
  matrix:
    - Build: mingw

install:
  - set PATH=%PATH%;C:\MinGW\bin;C:\MinGW\msys\1.0\bin
  #- dir C:\MinGW\msys\1.0\bin
  #These are already installed: mingw32-base msys-coreutils msys-wget
  - mingw-get.exe install mingw32-pthreads-w32
  - choco install pkgconfiglite
  - ps: |
      # Remove path to Git bin directory from PATH because it breaks MinGW config.
      $env:PATH = $env:PATH -replace "C:\\Program Files \(x86\)\\Git\\bin",""
      $env:PATH = $env:PATH -replace "C:\\Program Files\\Git\\bin",""
  - sh: sh mount C:\MinGW /mingw
  - mkdir ..\libs
  - cd ..\libs
  # uuid
  - appveyor DownloadFile https://gnome-build-stage-1.googlecode.com/files/uuid-1.6.2.tar.gz
  - tar -zxvf uuid-1.6.2.tar.gz
  - cd uuid-1.6.2
  - sh ./configure
  - C:\MinGW\msys\1.0\bin\make.exe
  # Hack to work around shtool on Windows not quoting enough
  - C:\MinGW\msys\1.0\bin\make.exe install || true
  # protobuf
  - cd ..
  - appveyor DownloadFile https://github.com/google/protobuf/releases/download/2.6.1/protobuf-2.6.1.zip
  # The tar doesn't extract properly, so grab the zip and use 7z
  - 7z x protobuf-2.6.1.zip
  - dir
  - cd protobuf-2.6.1
  - sh ./configure
  - C:\MinGW\msys\1.0\bin\make.exe
  - C:\MinGW\msys\1.0\bin\make.exe install
  # cppunit
  - cd ..
  - appveyor DownloadFile http://sourceforge.net/projects/cppunit/files/cppunit/1.12.1/cppunit-1.12.1.tar.gz/download -FileName cppunit-1.12.1.tar.gz
  - tar -zxvf cppunit-1.12.1.tar.gz
  - cd cppunit-1.12.1
  - sh ./configure
  - C:\MinGW\msys\1.0\bin\make.exe
  - C:\MinGW\msys\1.0\bin\make.exe install
  # liblo - Move this below libmicrohttpd when that's working
  - cd ..
  - appveyor DownloadFile http://sourceforge.net/projects/liblo/files/liblo/0.28/liblo-0.28.tar.gz/download -FileName liblo-0.28.tar.gz
  - tar -zxvf liblo-0.28.tar.gz
  - cd liblo-0.28
  - sh ./configure
  - C:\MinGW\msys\1.0\bin\make.exe
  - C:\MinGW\msys\1.0\bin\make.exe install
  # libmicrohttpd
  - cd ..
  - appveyor DownloadFile http://ftp.gnu.org/gnu/libmicrohttpd/libmicrohttpd-0.9.38.tar.gz
  - tar -zxvf libmicrohttpd-0.9.38.tar.gz
  - dir
  - cd libmicrohttpd-0.9.38
  - sh ./configure
  - C:\MinGW\msys\1.0\bin\make.exe
  - C:\MinGW\msys\1.0\bin\make.exe install
  # All done, get back to the right place
  - cd ../ola

before_build:
  #- set CPPFLAGS="-I/usr/local/include"
  #- set LDFLAGS = "-L/usr/local/lib"
  #- set PKG_CONFIG_PATH = "/usr/local/lib/pkgconfig"

build_script:
  - echo %PATH%
  - sh C:\MinGW\bin\autoreconf -i -f
  - sh ./configure --enable-python-libs --disable-all-plugins --enable-artnet --enable-dummy --enable-espnet --enable-kinet --enable-opendmx --enable-osc --enable-pathport --enable-sandnet --enable-shownet
  - C:\MinGW\msys\1.0\bin\make.exe

test_script:
  - C:\MinGW\msys\1.0\bin\make.exe check

on_failure:
  - appveyor PushArtifact config.log
  - appveyor PushArtifact test-suite.log
  - appveyor AddTest test

cache:
  - C:\projects\libs\uuid-1.6.2
  - C:\projects\libs\protobuf-2.6.1
  - C:\projects\libs\cppunit-1.12.1
  - C:\projects\libs\liblo-0.28
