environment:
  matrix:
    - Build: mingw

install:
  - set PATH=%PATH%;C:\MinGW\bin;C:\MinGW\msys\1.0\bin
  #These are already installed: mingw32-base msys-coreutils msys-wget
  - mingw-get.exe install mingw32-pthreads-w32 mingw32-gcc
  - choco install pkgconfiglite
  - ps: |
      # Remove path to Git bin directory from PATH because it breaks MinGW config.
      $env:PATH = $env:PATH -replace "C:\\Program Files \(x86\)\\Git\\bin",""
      $env:PATH = $env:PATH -replace "C:\\Program Files\\Git\\bin",""
  - sh: sh mount C:\MinGW /mingw
  - mkdir ..\libs
  - cd ..\libs
  - appveyor DownloadFile https://gnome-build-stage-1.googlecode.com/files/uuid-1.6.2.tar.gz
  - tar -zxvf uuid-1.6.2.tar.gz
  - dir
  - cd uuid-1.6.2
  - sh ./configure
  - sh make
  - sh make install

before_build:
  #- set CPPFLAGS="-I/usr/local/include"
  #- set LDFLAGS = "-L/usr/local/lib"
  #- set PKG_CONFIG_PATH = "/usr/local/lib/pkgconfig"

build_script:
  - echo %PATH%
  - sh C:\MinGW\bin\autoreconf -i -f
  - sh ./configure --enable-python-libs --disable-all-plugins --enable-artnet --enable-dummy --enable-espnet --enable-kinet --enable-opendmx --enable-osc --enable-pathport --enable-sandnet --enable-shownet
  - make

test_script:
  make check

on_failure:
  - appveyor PushArtifact config.log
  - appveyor PushArtifact test-suite.log
  - appveyor AddTest test
