environment:
  matrix:
    - Build: mingw

install:
  - set PATH=%PATH%;C:\MinGW\bin
  - C:\MinGW\bin\mingw-get.exe --help
  #These are already installed: mingw32-base msys-coreutils msys-wget
  - C:\MinGW\bin\mingw-get.exe install mingw32-pthreads-w32-dev

before_build:
  - set CPPFLAGS="-I/usr/local/include"
  - set LDFLAGS = "-L/usr/local/lib"
  - set PKG_CONFIG_PATH = "/usr/local/lib/pkgconfig"

build_script:
  - autoreconf -i -f
  - ./configure --enable-python-libs --disable-all-plugins --enable-artnet --enable-dummy --enable-espnet --enable-kinet --enable-opendmx --enable-osc --enable-pathport --enable-sandnet --enable-shownet
  - make

test_script:
  - make check

on_failure:
  - appveyor PushArtifact test-suite.log
  - appveyor AddTest test
